### ISSUE TITLE
SEO of website

### ISSUE THREAD

**Issue by sudopluto** [triplea-game/triplea-game.github.io#128] opened 2016-12-08 20:59 UTC
When searching for the game, the old sourceforge site comes up for the first result, while the actual site comes up way later.

**Comment by DanVanAtta** [comment] 2016-12-17 00:53
Indeed, the SEO needs some help. We've linked to the new website from the source forge page, which should help some. Any recommendations or suggestions to help improve it?

**Comment by RoiEXLab** [comment] 2017-01-08 03:35
A suggestion I read very often is 301 redirects, but I believe we don't have access to that...
Also I heard that is possible to tell Google your website moved in the webmaster tools...

**Comment by kskarthik** [comment] 2017-01-30 09:30
I will look into this :) in a simple way

**Comment by RoiEXLab** [comment] 2017-08-27 17:14
The Website is still behind source forge, but it is in the first couple of results, which should be good enough.
Closing this issue for now

**Comment by DanVanAtta** [comment] 2017-08-28 16:43
Let's keep tracking, this is still a problem as reported, the issue is that the current site is still below the old results. We are missing some action items though, we should identify some things we can do to improve this situation. If we exhaust all practical suggestions and this is still a problem, then I recommend we close at that time given there is not much further we would be able to do.

With that, is there a list of some things we can look into to try and boost our SEO? Maybe start a forum campaign to get people to link to us? Is there something in google we can do to tell them about the new official website, basically follow up with: "Also I heard that is possible to tell Google your website moved in the webmaster tools..."

It does seem like there is both a problem and some next steps to take, so will re-open to keep tracking for a bit longer.

**Comment by RoiEXLab** [comment] 2017-08-28 16:54
@DanVanAtta You're right: There are actions we haven't tried yet.
Google has a guide on how to move a site: https://support.google.com/webmasters/answer/6033049?hl=en
What are our actual options given that we don't have full control of the sourceforge server?
DOes anyone have this site mapped to a webmaster account on google?

**Comment by DanVanAtta** [comment] 2017-08-28 17:25
@ron-murhammer should have full source forge permissions, if not we can get Veqryn.

**Comment by RoiEXLab** [comment] 2017-08-28 17:30
By "not full control" I meant that we don't have access to the actual server software e.g. nginx or apache, which probably makes adding 301 requests really hard/impossible

**Comment by RoiEXLab** [comment] 2017-08-28 17:31
Also feel free to correct me if I'm wrong.

**Comment by DanVanAtta** [comment] 2017-08-28 17:35
I'm sure other projects have been in a similar situation. There may be nothing we can do in that case, but maybe there is.

We should not also get tunnel vision on the one approach, there are other classic SEO strategies we could pursue.

**Comment by RoiEXLab** [comment] 2017-12-01 09:05
The sourceforge websites now 301 redirects to triplea-game.org and forums.triplea-game.org
I believe there's nothing more to do than to wait for the google bots to detect the 301 redirection

**Closed by RoiEXLab** 2017-12-01 09:05 UTC

**Comment by RoiEXLab** [comment] 2017-12-01 18:53
Using a free proxy and googling for just "triplea" makes it appear as the first search engine result 🎉 
The same for "triplea forum" with the forum.
Seems like we did it

**Comment by RoiEXLab** [comment] 2017-12-03 22:25
Just for the record: I added a google verification file for triplea-game.org to initiate a site migration at google in commit https://github.com/triplea-game/triplea-game.github.io/commit/a85fb72e9bf5ba4d01ca6b5f7ce6fc0464dac3db
triplea.sourceforge.net should now vanish pretty quickly from the search results
