### ISSUE TITLE
Rework legacy documentation

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea-game.github.io#216] opened 2017-06-05 17:28 UTC
The legacy documents are well legacy.
They are everything but up-to-date.
It should be our long-term-goal to completely replace this documentation with a new one which should have about the same content, but up-to-date.

Leaving this here as a reminder

**Comment by DanVanAtta** [comment] 2017-06-05 17:44
Thanks for creating the reminder task. I would suggest instead of replacing we delete or update the out of date, and try to fix the still valid documentation to be more concise. Example, instead of paragraphs, see if we can say the same in a sentence. There is too much over-explanation, and a good bit of redundant explanation too.

Some details to consider:
- https://github.com/triplea-game/triplea/issues/1775 is discussing which documentation to move out of the website, likely would be at least the developer documentation
- forum documentation, notably the stuff on source forge. Should we try to consolidate that into the website? It is a bit legacy in some respects, particularly the map download help, and it could use pruning.


As a process note @RoiEXLab  for us to think about - tickets/issues that we cannot close readily cause a number of operation overhead problems. Notably we get into a pattern of scanning and filtering the ticket queue which would grow over time (since we cannot zero it out) instead of always being able to take the bottom issue and work on it to completion. For this issue, I think the issue is good, but once we have discussed the topic, I would suggest perhaps a line item in a long-term project wiki page would be a better reminder that we have this project (or maybe github projects would be good for this??). Ultimately I'd like us to strive for github issues that we always know what to do with based on the last comment and/or overview, and that we can always do something to work on to close them. If not, my hope is that we can track those items in a different queue/location.

**Comment by RoiEXLab** [comment] 2017-06-05 17:54
Good Points @DanVanAtta 
You're right about the long-term issues, I just think since the website repo doesn't have too many tasks it's not that important...
Yeah, deleting the old documentation is probably the right thing. Although (or probably because) it's very old it provides a lot of details. We really need to get the same amount of content into the "current" documentation

**Comment by DanVanAtta** [comment] 2017-08-25 00:38
Closing for now, there is no open action item that I can tell. We can cut new issues to discuss future changes, the docs need a *lot* of work content wise. The current state is most of it is has been lumped together, and some of it pruned, but it is mostly just lumped. So at least we no longer have stuff in so many places, but it's documentation that is spread out over 15 years and is duplicated across itself.. PRs to clean-up and simplify are deeply welcome.

**Comment by DanVanAtta** [comment] 2017-08-25 00:39
We can also discuss strategies for how to re-work, feel free to open a new topic if interested in picking that up, or proposing changes directly in a PR

**Closed by DanVanAtta** 2017-08-25 00:38 UTC
Labels: Documentation
